name: Feature request
description: Suggest an improvement for Shifra.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your proposed solution
    validations:
      required: true
